'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {Service,projectView,snapshotView}=require('./static/service.js');
const {APIError}=require('./static/api.js');
const model=require('./static/model.js');
const lifecycle=require('./static/lifecycle.js');
const stamp='2026-10-10T02:00:00Z';
const snapshot=(id='a',generation=0,revision=1)=>({graph:{project:{id,title:id,scenario:'pentest',status:'active',orchestration_version:1,generation,created_at:stamp},facts:[{id:'origin',description:'https://authorized.test',created_at:stamp},{id:'goal',description:'Find supported evidence',created_at:stamp}],intents:[],hints:[]},goals:[],steps:[],fact_records:[],findings:[],revision});
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
function fixture(states={a:snapshot()}){const calls=[];return {calls,async request(url,options={}){calls.push({url,options});if(url==='/projects')return Object.values(states).map(s=>s.graph.project);const [,id,suffix]=url.match(/^\/projects\/([^/]+)(.*)$/)||[];const state=states[id];if(suffix==='/state')return state;if(suffix==='/identity')return {id,generation:state.graph.project.generation};if(suffix==='/inputs')return [];if(suffix?.startsWith('/rounds'))return {items:[]};if(suffix?.startsWith('/state/events'))return [];throw new Error(url);},async projectExecutions(){return []}};}
test('production shell is the demo document structure with real network access and no fixture routes',()=>{const html=fs.readFileSync(path.join(__dirname,'static/index.html'),'utf8'),app=fs.readFileSync(path.join(__dirname,'static/app.js'),'utf8');assert.match(html,/<main id="main"><\/main>/);assert.match(html,/data-create/);assert.match(html,/project-menu-popover/);assert.match(html,/connect-src 'self'/);assert.doesNotMatch(html,/simulate-failure|workbench\.css|models\.css|#project\/atlas/);assert.doesNotMatch(app,/atlas\.example|local-.*randomUUID|模拟本次操作|lifecycle\.apply/);assert.match(app,/PwnLLMDemo\.render/);assert.match(app,/class="workspace-actions"/);});
test('project adapter maps server lifecycle without fabricating findings or times',()=>{const state=snapshot(),p=snapshotView(state,[],[],[]);assert.equal(p.name,'a');assert.equal(p.target,'https://authorized.test');assert.equal(p.goal,'Find supported evidence');assert.equal(p.status,'running');assert.equal(p.endedAt,null);assert.deepEqual(p.state.findings,[]);for(const [status,expected] of [['stopped','paused'],['completed','done'],['terminated','terminated']])assert.equal(projectView({...state.graph.project,status}).status,expected);});
test('historical projects are read-only when the server omits or explicitly sends protocol zero',()=>{
 for(const version of [undefined,0])for(const status of ['active','stopped','completed','terminated']){
  const raw={...snapshot().graph.project,status};if(version===undefined)delete raw.orchestration_version;else raw.orchestration_version=version;
  const p=projectView(raw);assert.equal(p.readOnly,true);assert.deepEqual(lifecycle.actions(p),[]);assert.equal(lifecycle.canHint(p),false);
 }
 const current=projectView(snapshot().graph.project,{readOnly:true});assert.equal(current.readOnly,false);assert.deepEqual(lifecycle.actions(current),['pause','restart','terminate','delete']);assert.equal(lifecycle.canHint(current),true);
 assert.deepEqual(lifecycle.actions({...current,archived:true}),[]);assert.equal(lifecycle.canHint({...current,archived:true}),false);
});
test('refresh fetches real materials, round summaries and generation-fenced state',async()=>{const api=fixture(),service=new Service(api);const value=await service.refresh('a');assert.equal(value.selected.id,'a');assert.ok(api.calls.some(c=>c.url==='/projects/a/inputs'));assert.ok(api.calls.some(c=>c.url.startsWith('/projects/a/rounds?')));assert.ok(api.calls.some(c=>c.url==='/projects/a/identity'));});
test('late project responses cannot replace the latest selection even if transport ignores abort',async()=>{const api=fixture({a:snapshot(),b:snapshot('b')}),old=api.request.bind(api),gate=deferred();api.request=(url,opts)=>url==='/projects/a/state'?gate.promise:old(url,opts);const service=new Service(api),first=service.refresh('a');await new Promise(r=>setImmediate(r));await service.refresh('b');gate.resolve(snapshot());assert.equal(await first,null);assert.equal(service.projects.find(p=>p.id==='b').state.graph.project.id,'b');});
test('generation conflict refuses mixed current and previous round data',async()=>{const api=fixture(),old=api.request.bind(api);api.request=(url,opts)=>url.endsWith('/identity')?{id:'a',generation:1}:old(url,opts);const service=new Service(api);await assert.rejects(service.refresh('a'),error=>error.status===409);assert.deepEqual(service.projects,[]);});
test('failed refresh preserves the last accepted project state',async()=>{const api=fixture(),service=new Service(api);await service.refresh('a');const before=service.projects;api.request=()=>{throw new APIError('offline');};await assert.rejects(service.refresh('a'),/offline/);assert.equal(service.projects,before);});
test('refresh filters executions from old rounds and bounds event projection to state revision',async()=>{const state=snapshot('a',2,2),api=fixture({a:state}),old=api.request.bind(api);api.projectExecutions=async()=>[{id:'old',generation:1},{id:'current',generation:2}];api.request=(url,opts)=>url.includes('/state/events?')?[{revision:2,op:'event'},{revision:3,op:'event'}]:old(url,opts);const service=new Service(api),result=await service.refresh('a');assert.deepEqual(result.selected.runs.map(r=>r.id),['current']);assert.equal(result.selected.events.length,1);assert.equal(service.events.get('a').after,3);});
test('project creation retries only unfinished uploads on the same paused project',async()=>{const calls=[],files=[new File(['a'],'a.txt'),new File(['b'],'b.txt')];let fail=true;const service=new Service({async request(url,options){calls.push({url,options});return {project:{id:'created'}};},async uploadInput(base,file){calls.push({upload:file.name});if(file.name==='b.txt'&&fail){fail=false;throw new APIError('upload interrupted',503);}}});const values={name:'Test',type:'pentest',target:'authorized',goal:'evidence',files};await assert.rejects(service.create(values),error=>error.pendingCreate);assert.equal(calls[0].options.body.start_paused,true);assert.equal(await service.create(values),'created');assert.equal(calls.filter(c=>c.url==='/projects').length,1);assert.deepEqual(calls.filter(c=>c.upload).map(c=>c.upload),['a.txt','b.txt','b.txt']);assert.deepEqual(calls.at(-1).options.body,{status:'active'});});
test('ambiguous creation is never blindly retried',async()=>{let creates=0;const service=new Service({async request(){creates++;throw new APIError('lost connection',0);}}),values={name:'Test',type:'pentest',target:'authorized',goal:'evidence',files:[]};await assert.rejects(service.create(values),error=>error.uncertainCreate);await assert.rejects(service.create(values),/尚未确认/);assert.equal(creates,1);});
test('lifecycle operations use real endpoints and generation fencing',async()=>{const calls=[],service=new Service({async request(url,options){calls.push({url,options});}});for(const action of ['pause','resume','restart','terminate','delete'])await service.change('a/b',action,7);assert.equal(calls[0].url,'/projects/a%2Fb/status');assert.deepEqual(calls[0].options.body,{status:'stopped'});assert.deepEqual(calls[2].options.body,{expected_generation:7});assert.equal(calls.at(-1).options.method,'DELETE');});
test('supplement files and text use one atomic batch request',async()=>{const calls=[],file=new File(['bytes'],'request.http'),service=new Service({async uploadInputs(...args){calls.push(args);},async request(...args){calls.push(args);}});await service.hint('a',{text:'scope',files:[file]});assert.equal(calls.length,1);assert.equal(calls[0][1][0],file);assert.equal(calls[0][2],'scope');await service.hint('a',{text:'more scope',files:[]});assert.equal(calls[1][0],'/projects/a/hints');});
test('form drafts retain actual File objects and validate total uploaded bytes',()=>{const file=new File(['raw bytes'],'request.http'),drafts=model.createFormDrafts();drafts.setCreate({name:'Test',type:'pentest',target:'scope',goal:'evidence',files:[file]});assert.equal(drafts.getCreate().files[0],file);assert.match(model.validateFiles([{name:'large.zip',size:257*1048576}]),/256/);assert.match(model.validateFiles(Array.from({length:33},(_,i)=>({name:i+'.txt',size:1}))),/32/);});
test('real log projection preserves timestamps and evidence rather than fixture narrative',()=>{const activity=require('./static/activity-data.js'),p={logs:[{id:'x',title:'Real event',body:'evidence',time:stamp,node:{type:'fact',id:'proof'},artifacts:[{path:'file.txt',excerpt:'actual'}]}]};const entries=activity.buildEntries(p);assert.equal(entries.length,1);assert.equal(entries[0].timestamp,stamp);assert.equal(entries[0].key,'fact:proof');assert.match(entries[0].evidence,/actual/);assert.deepEqual(activity.buildEntries({}),[]);});

test('archive hydration survives a concurrent live refresh without losing the selected round',async()=>{
 const oldState=snapshot('a',0),liveState=snapshot('a',1),api=fixture({a:liveState}),original=api.request.bind(api),gate=deferred();
 const bytes=Buffer.from(JSON.stringify(oldState));
 api.request=(url,options)=>{if(url==='/projects/a/rounds?limit=100&cursor=-1')return {items:[{generation:0,archived_at:'2026-10-10T03:00:00Z'}]};if(url==='/projects/a/rounds/0/entries?limit=100&cursor=0')return {items:[{cursor:1,kind:'state',id:'state',bytes:bytes.length}]};if(url.startsWith('/projects/a/rounds/0/entries/1?'))return gate.promise;return original(url,options);};
 const service=new Service(api);await service.refresh('a');const before=service.projects[0],loading=service.archive(before,0);await new Promise(resolve=>setImmediate(resolve));await service.refresh('a');
 gate.resolve({encoding:'base64',offset:0,total_bytes:bytes.length,data:bytes.toString('base64')});await loading;
 assert.equal(service.projects[0].history[0].state.graph.project.generation,0);assert.equal(service.projects[0].history[0].archived,true);assert.equal(service.projects[0].state.graph.project.generation,1);
});
test('archived UTF-8 state chunks join without corrupting a split multibyte character',async()=>{
 const state=snapshot('a',0);state.graph.project.title='中文项目';const bytes=Buffer.from(JSON.stringify(state)),split=bytes.indexOf(Buffer.from('中文'))+1;
 const summary={id:'a',generation:0,archivedAt:stamp,files:[]},project={id:'a',history:[summary]};
 const service=new Service({async request(url){if(url.endsWith('/entries?limit=100&cursor=0'))return {items:[{cursor:1,kind:'state',bytes:bytes.length}]};const offset=Number(new URL(url,'http://local').searchParams.get('offset'));return {encoding:'base64',offset,total_bytes:bytes.length,data:bytes.subarray(offset,offset?bytes.length:split).toString('base64'),...(offset?{}:{next_offset:split})};}});service.projects=[project];const archived=await service.archive(project,0);assert.equal(archived.name,'中文项目');
});
